services:
  hotel-discovery-service:
    build: ./DiscoveryService
    container_name: hotel-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8761/actuator/health" ]
      interval:  5s
      retries: 2
  hotel-config-service:
    build: ./ConfigService
    container_name: hotel-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9999/actuator/health" ]
      interval: 5s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://hotel-discovery-service:8761/eureka
    depends_on:
      hotel-discovery-service:
        condition: service_healthy
  hotel-chambre-service:
    build: ./Chambre
    container_name: hotel-chambre-service
    ports:
      - '9000:9000'
    expose:
      - '9000'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9000/actuator/health" ]
      interval: 5s
      retries: 6
    environment:
      - DISCOVERY_SERVICE_URL=http://hotel-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://hotel-config-service:9999
    depends_on:
      hotel-config-service:
        condition: service_healthy
  hotel-client-service:
    build: ./Client
    container_name: hotel-client-service
    ports:
      - '9001:9001'
    expose:
      - '9001'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9001/actuator/health" ]
      interval: 5s
      retries: 8
    environment:
      - DISCOVERY_SERVICE_URL=http://hotel-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://hotel-config-service:9999
    depends_on:
      hotel-chambre-service:
        condition: service_healthy
  hotel-reservation-service:
    build: ./Reservation
    container_name: hotel-reservation-service
    ports:
      - '9002:9002'
    expose:
      - '9002'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9002/actuator/health" ]
      interval: 5s
      retries: 10
    environment:
      - DISCOVERY_SERVICE_URL=http://hotel-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://hotel-config-service:9999
    depends_on:
      hotel-client-service:
        condition: service_healthy
  hotel-gitway-service:
    build: ./Gitway
    container_name: hotel-gitway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      retries: 12
    environment:
      - DISCOVERY_SERVICE_URL=http://hotel-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://hotel-config-service:9999
    depends_on:
      hotel-reservation-service:
        condition: service_healthy